services:
  db:
    image: postgres:17
    container_name: twiker-postgres
    hostname: twiker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data
      - ./db-init/twiker_dump.sql:/docker-entrypoint-initdb.d/twiker_dump.sql

  redis:
    image: "redis"
    container_name: twiker-redis
    hostname: twiker-redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"

  twiker-app:
    image: libright1558/twiker-app-dev:v1
    build: 
      dockerfile: twiker-app-dev.dockerfile
      context: .
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    container_name: twiker-app-dev-container
    hostname: twiker-app-dev

  proxy:
    image: nginx
    container_name: nginx-container
    hostname: nginx
    depends_on:
      - twiker-app
    ports:
      - "80:80"
    volumes:
      - ./nginx/twiker.conf:/etc/nginx/conf.d/twiker.conf

volumes:
  postgres_dev: